### ISSUE TITLE
Chatgpt

### ISSUE THREAD

**Issue by shayan823** [microsoft/promptbench#10]
I want to replicate the results in the paper using the chatgpt model. But `predict_by_openai_api` method raises an error, i.e. NotImplementedError.

**Comment by Immortalise** [comment]
Hi,

For the utilization of ChatGPT, please refer to the instructions on the [OpenAI API website](https://platform.openai.com/docs/introduction) to construct the predict function in inference.py.

**Comment by jindongwang** [comment]
@shayan823 We do not offer code for ChatGPT api since calling OpenAI API is considered the common approach for today's LLM research (you can easily find it on OpenAI website).
