### ISSUE TITLE
Potentially a bug in `LabelConstraint`

### ISSUE THREAD

**Issue by SagiPolaczek** [microsoft/promptbench#11]
Hello,
Firstly, thanks for your contribution and open-sourcing you code!

I got the following error trying to reproduce an attack for the SST2 dataset:
```
  File "<PATH>/promptbench/prompt_attack/label_constraint.py", line 12, in <listcomp>
    self.labels = [label.lower() for label in labels]
AttributeError: 'int' object has no attribute 'lower'
```

Which makes sense since in the config the labels consist integers:
```python
    'sst2': ['positive', 'negative', 'positive\'', 'negative\'', '0', '1', '0\'', '1\'',0, 1], 
```
But in the `LabelConstraint` constructor we have:
```python
    def __init__(self, labels=[]):
        self.labels = [label.lower() for label in labels]
```

The changes were made in [this PR](https://github.com/microsoft/promptbench/commit/3c3c8d9de619911fee59b3adc600921c6d307210).

To make it run we can simply delete the integers labels `0, 1` - tho I'm afraid the ground truth labels might be integers.
So another solution could be to apply`.lower()` only on string labels (which to me sounds like the correct approach).

What do you guys think?

**Comment by Immortalise** [comment]
Hi,

Thank you for bringing this potential error to our attention. We will address it right away. Initially, we considered using integer labels, but later decided not to use them. Removing them should suffice.

Thanks once again!
