### ISSUE TITLE
transferibility app error

### ISSUE THREAD

**Issue by ogencoglu** [microsoft/promptbench#12]
Error in transferibility app from chatgpt to Vicuna

![image](https://github.com/microsoft/promptbench/assets/8182738/93cd436c-d98c-4e9e-9eaa-06e40e5b028e)

**Comment by jindongwang** [comment]
This must be a bug. We'll fix this later.

**Comment by Immortalise** [comment]
Hi,

Thank you for bring this bug to our attention, now the bug is fixed :)

**Comment by ogencoglu** [comment]
Thanks for the swift fix.
