### ISSUE TITLE
Can you please explain how to interpret the output on the main/examples/basic.ipynb

### ISSUE THREAD

**Issue by jacobweiss2305** [microsoft/promptbench#38]
Can you please explain how to interpret the metrics for the last cell on main/examples/basic.ipynb?

https://github.com/microsoft/promptbench/blob/main/examples/basic.ipynb

![image](https://github.com/microsoft/promptbench/assets/26749795/1f009c89-b07c-4334-bfb6-e4238d3e0f25)

**Comment by jacobweiss2305** [comment]
What is the .947 mean? Maybe there is a formula you can point us to, also?

**Comment by jacobweiss2305** [comment]
It looks like a standard accuracy metric. How many the bot answered correctly divide by total responses?

The data is pre-labelled so thats my best guess.

**Comment by Millz98** [comment]
> What is the .947 mean? Maybe there is a formula you can point us to,?

That looks like an accuracy score

**Comment by Millz98** [comment]
> It looks like a standard accuracy metric. How many the bot answered correctly divide by total responses?
> 
> The data is pre-labelled so thats my best guess.

Yes reviewing the code you showed it seems to be the prediction score with an accuracy of 94% on each section it is evaluating.

**Comment by Immortalise** [comment]
Hi, Millz98 is right, 0.947 means accuracy of this prompt.
