### ISSUE TITLE
Interpretation of attack results

### ISSUE THREAD

**Issue by xipq** [microsoft/promptbench#39]
Thanks for this amazing repo on evaluating differet prompts, and I am keen to apply it to more LLMs 🤗

 I tried to evaluate the prompt attack following your example, and obtained the following output:
`(0.0, "Aѕ a sentiment classifier, determine whether the following text is 'positive' or 'negative'. Please classify: \nQuestion: {content}\nAnswer:  ", 0.0, 0.0)`

I would like to know how to intepretate these numbers, and more importantly how can I obtain the evaluation results like in `promptbench/prompt_attack/README.md`? Since I haven't found related information in your documents. Am i missing something?

Thank you very much!

**Comment by Immortalise** [comment]
Hi,

Thanks for bringing this issue to us! We have modified the code, please clone the most recent repository and see if there are any further issues.

Currently, the output will be:
```
...

--------------------------------------------------
Current prompt is:  As a sentiment classifier, determine whether the following text is 'positive' or 'negative'. Please classify: 
Question: {content}
Answer  and true is true :
Current accuracy is:  1.0
--------------------------------------------------

{'original prompt': "As a sentiment classifier, determine whether the following text is 'positive' or 'negative'. Please classify: \nQuestion: {content}\nAnswer:", 'original score': 1.0, 'attacked prompt': "As a sentiment classifier, determine whether the following text is 'positive' or 'negative'. Please classify: \nQuestion: {content}\nAnswer  and false is not true :", 'attacked score': 1.0, 'PDR': 0.0}
```

**Comment by xipq** [comment]
Thanks four your updates
