### ISSUE TITLE
ChatGPT version

### ISSUE THREAD

**Issue by titaniumrain** [microsoft/promptbench#4]
May we please confirm with you the exact ChatGPT version you used in the paper? Thanks.

**Comment by Immortalise** [comment]
Hi, the version of ChatGPT we're using is "gpt-3.5-turbo". For further details, you can refer to OpenAI's official documentation [here](https://platform.openai.com/docs/models/gpt-3-5).

**Comment by maddogwithrabies** [comment]
Thank you for your prompt reply. Much appreciated!
