### ISSUE TITLE
Enhancement Proposal for Dynamic Evaluation Framework Integration

### ISSUE THREAD

**Issue by yihong1120** [microsoft/promptbench#43]
Dear PromptBench Contributors,

I trust this message finds you in good health and high spirits. I am writing to propose an enhancement to the PromptBench library that I believe could significantly augment its utility for researchers and practitioners alike.

Having perused the documentation and utilised the library extensively, I have found the dynamic evaluation framework, DyVal, to be an invaluable asset for assessing the performance of Large Language Models (LLMs) in a more robust and realistic manner. However, I have observed that the integration of DyVal could be further refined to provide a more seamless user experience and to extend its capabilities.

To wit, I propose the following enhancements:

1. **Streamlined Integration**: Simplifying the process of setting up and running DyVal within the PromptBench environment. This could involve automating the setup process and providing a more intuitive API that abstracts away some of the complexities involved in configuring the dynamic evaluation parameters.

2. **Extended Dataset Support**: Expanding the range of datasets compatible with DyVal. While the current selection is commendable, incorporating additional datasets, particularly from niche domains, could broaden the scope of dynamic evaluation and provide deeper insights into model performance across diverse contexts.

3. **Custom Evaluation Metrics**: Facilitating the integration of custom evaluation metrics within the DyVal framework. This would allow researchers to define and utilise metrics that are specifically tailored to their unique research questions or application requirements.

4. **Real-time Performance Monitoring**: Introducing functionality for real-time monitoring of model performance during dynamic evaluation. This could include visual dashboards or logging mechanisms that provide immediate feedback on the model's performance trends over time.

5. **Guidance on Best Practices**: Providing comprehensive documentation and examples that elucidate best practices for leveraging DyVal in various research scenarios. This could greatly assist users in maximising the potential of dynamic evaluation for their specific use cases.

I am keen to engage in further dialogue regarding these suggestions and explore how we might collaborate to bring these enhancements to fruition. I am convinced that by enriching the DyVal integration, PromptBench can offer even greater value to the community by enabling more nuanced and insightful evaluation of LLMs.

Thank you for considering my proposal. I eagerly anticipate your response and am hopeful for the opportunity to contribute to the evolution of PromptBench.

Best regards,
yihong1120

**Comment by Immortalise** [comment]
Hi Yihong,

Thank you for your suggestions about enhancing PromptBench with DyVal integration. We appreciate your valuable suggestions and eager to discuss how we can collaborate. Could you share your thoughts on how we might work together on this? (P.S., feel free to initiate a pull request.)
