### ISSUE TITLE
How to add a new Model

### ISSUE THREAD

**Issue by minhopark-neubla** [microsoft/promptbench#44]
In this document (https://github.com/microsoft/promptbench/blob/53130af4ebc1d3bbc1b3a22871c60319acf5ec94/examples/add_new_modules.md?plain=1#L11)
A new model should be implemented in `dataload/model.py`. But there are no file in `dataload` and I think a directory is something weird. Do you think it's right guide?
All other models are implemented in here (https://github.com/microsoft/promptbench/blob/main/promptbench/models/models.py)

**Comment by Immortalise** [comment]
Ah, yes, thanks for pointing out this error! Models are implemented in `models/models.py` not in `dataload`.

**Comment by minhopark-neubla** [comment]
+ https://arxiv.org/abs/2312.07910 also looks like it needs to be revised.
