### ISSUE TITLE
Is this an ongoing project?

### ISSUE THREAD

**Issue by tarikaltuncu** [microsoft/promptbench#48]
As you still do not support `gpt-4-0125-preview`, I assume this is a dead project? Is it?

**Comment by Immortalise** [comment]
Thank you for your reminder. We now support the newest OpenAI GPT models.

This project is very much alive. Given that adding support for new OpenAI models is a straightforward task, we believe it can be easily accomplished by talented researchers. We welcome and encourage code contributions from the community.

**Comment by tarikaltuncu** [comment]
Thanks. I just wanted to check if there are maintainers. Best
