### ISSUE TITLE
Where is defined inference_total_dataset()

### ISSUE THREAD

**Issue by dmitrysarov** [microsoft/promptbench#49]
https://github.com/microsoft/promptbench/blob/fff2d1f0c075191fa80fe3efc264fcc7e3c031d6/promptbench/prompt_attack/attack.py#L208
Please point me where defined this function

**Comment by Immortalise** [comment]
Hi, thanks for bringing this bug to us! Now it is fixed. BTW, it is supposed to implement a eval_func when perform prompt attacks. The interface is eval_func(prompt, dataset, model), in this function, you need to implement the logic to get the prediction of the model on the prompt, and evaluate the correctness of the prediction, finally, return the accuracy of the model on the prompt.
