### ISSUE TITLE
About black-box attacks

### ISSUE THREAD

**Issue by zhouzihao501** [microsoft/promptbench#5]
hey, I want to know the details in the gpt attack.

Is your attack like this?:
For a sample which original is true. After you add an attack prompt and its output is wrong, then it means attack is successful?

Because in score-base attack, the output probabilities will decrease, like this: 1.0->0.8->0.5->0.4
And in your method, it is like that?: 1.0->0
Thanks

**Comment by Immortalise** [comment]
Hi Zihao,

Yes, the aim of prompt attacks on LLMs is to alter their predictions to be wrong. These attacks don't consider probability variations.
