### ISSUE TITLE
How do you get the evaluation results of the `prompt enginering` leaderboard?

### ISSUE THREAD

**Issue by zhimin-z** [microsoft/promptbench#50]
Check https://promptbench.readthedocs.io/en/latest/leaderboard/pe.html:
![image](https://github.com/microsoft/promptbench/assets/8592144/2c3593e9-7e6a-4fb6-8f76-2aaf56528468)
I failed to locate any related report or paper that could reproduce these evaluation results...
@madhavMathur @jindongwang @msftgits @dnfclas

**Comment by zhimin-z** [comment]
Check the original [PromptBench](https://llm-eval.github.io/pages/leaderboard/advprompt.html) paper but unfortunately, there is no related benchmark:
![image](https://github.com/microsoft/promptbench/assets/8592144/9b084e55-14c9-418f-9193-bec81c8e0a5f)

**Comment by jindongwang** [comment]
@icecream-and-tea can answer this question

**Comment by icecream-and-tea** [comment]
For the sake of convenience in presentation, we only included the main part of the prompt engineering evaluation results in the paper. The evaluation of all data can be found in this page ( [ https://promptbench.readthedocs.io/en/latest/leaderboard/pe.html](https://promptbench.readthedocs.io/en/latest/leaderboard/pe.html))

**Comment by zhimin-z** [comment]
> For the sake of convenience in presentation, we only included the main part of the prompt engineering evaluation results in the paper. The evaluation of all data can be found in this page ( [ https://promptbench.readthedocs.io/en/latest/leaderboard/pe.html](https://promptbench.readthedocs.io/en/latest/leaderboard/pe.html))

Add a PR accordingly: https://github.com/microsoft/promptbench/pull/58
