### ISSUE TITLE
The `prompt engineering` leaderboard is cut off in half...

### ISSUE THREAD

**Issue by zhimin-z** [microsoft/promptbench#51]
![image](https://github.com/microsoft/promptbench/assets/8592144/3f92b060-0cba-4119-8aa2-040312f55996)
The second leaderboard seems to be part of the first one (since it does not come with any **name** on top like the first one) but it is cut off mysteriously...
Check https://llm-eval.github.io/pages/leaderboard/pe.html

**Comment by zhimin-z** [comment]
Additionally, consider merging the initial cells in the first row into a single cell. Currently, the segmented display somehow detracts from the overall readability and aesthetic appeal.
![image](https://github.com/microsoft/promptbench/assets/8592144/299eced8-51d1-4411-93e9-c125c6a8aa78)

**Comment by jindongwang** [comment]
@zhimin-z Merged your PR
