### ISSUE TITLE
The ‘temperature’ parameter in pb.LLMModel needs to be of type float

### ISSUE THREAD

**Issue by ShiYu05** [microsoft/promptbench#53]
![1709090414095](https://github.com/microsoft/promptbench/assets/107471291/71671e5c-3da5-434b-b656-678d8063a6cc)

    """
    A class providing an interface for various language models.

    This class supports creating and interfacing with different language models, handling prompt engineering, and performing model inference.

    Parameters:
    -----------
    model : str
        The name of the model to be used.
    max_new_tokens : int, optional
        The maximum number of new tokens to be generated (default is 20).
    temperature : float, optional
        The temperature for text generation (default is 0).
    model_dir : str or None, optional
        The directory containing the model files (default is None).
    system_prompt : str or None, optional
        The system prompt to be used (default is None).
    openai_key : str or None, optional
        The OpenAI API key, if required (default is None).
    sleep_time : int, optional
        The sleep time between inference calls (default is 3).

**Comment by Immortalise** [comment]
Hi, thanks for bringing this to us! We have fixed this issue in the latest version.
