### ISSUE TITLE
Can you provide a general data format for constructing test data independently?

### ISSUE THREAD

**Issue by ShiYu05** [microsoft/promptbench#54]
While it’s great that you have integrated a lot of data, it feels like there’s still a lack of templates for users to customize and construct their own data sets. This would reduce the workload of integrating data sets and increase the flexibility of the framework.

**Comment by Immortalise** [comment]
Hi, you could find helpful tips [here](https://github.com/microsoft/promptbench/blob/main/examples/add_new_modules.md) and the [example datasets](https://github.com/microsoft/promptbench/blob/main/promptbench/dataload/dataset.py).
