### ISSUE TITLE
About Checklist attack method

### ISSUE THREAD

**Issue by Alex357853** [microsoft/promptbench#6]
Hi,

I was wondering why your implementation of Checklist attack method is different from the one in TextAttack package. Thank you for your time!

**Comment by Immortalise** [comment]
Hi,

The original implementation of [CheckList](https://aclanthology.org/2020.acl-main.442.pdf) contains various testing types (as shown in Table 1). Here we only focus on the 'robust' type, which adds a random url/handle at the end of a sentence.
