### ISSUE TITLE
Pip's dependency conflicts :datasets==2.15.0 

### ISSUE THREAD

**Issue by bg51717** [microsoft/promptbench#66]
I want to use this project to evaluate my models.Howerer,when I use the command:
```
pip install promptbench
```
It raise a error as the title.The promptbench require the datasets==2.15.0,but the other package require datasets==2.18.0.
So would you add the support for dataset==2.18.0 or other versions?Thanks.

**Comment by Immortalise** [comment]
Hi, thanks for bringing this issue for us. It will be fixed within one day.
