### ISSUE TITLE
Question-answer template attack

### ISSUE THREAD

**Issue by ary4n99** [microsoft/promptbench#74]
Hey, during the attacks conducted for the paper, was the question answer part of the prompt aka `\nQuestion: {content}\nAnswer:` attacked? Thank you!

**Comment by Immortalise** [comment]
Hi, thanks for your interest in prompt attacks! Regarding your question, the behavior you observed depends on the unmodifiable words you've set. Please check [this example notebook](https://github.com/microsoft/promptbench/blob/main/examples/prompt_attack.ipynb) on how to specify unmodifiable words. You could simply add ['Question', 'Answer'] into unmodifiable words.

In the output, you will see entries similar to the following:

```
--------------------------------------------------
Modifiable words:  ['As', 'a', 'sentiment', 'classifier', 'determine', 'whether', 'the', 'following', 'text', 'is', 'or', 'Please', 'classify', 'Question', 'Answer']
--------------------------------------------------
```

This will help you ensure that sections like `\nQuestion: {content}\nAnswer:` will not be attacked during the prompt attack process.
