### ISSUE TITLE
Attack goal function details

### ISSUE THREAD

**Issue by ary4n99** [microsoft/promptbench#75]
Hey, what's the reason behind using the difference in scores for the attack goal function instead of the PDR? 

https://github.com/microsoft/promptbench/blob/3daaf2d3734ec8c08302f73b93e640973a1edd41/promptbench/prompt_attack/goal_function.py#L276-L279

Also, why has `maximizable=True` not been passed to the goal function?

https://github.com/microsoft/promptbench/blob/3daaf2d3734ec8c08302f73b93e640973a1edd41/promptbench/prompt_attack/goal_function.py#L242-L248

**Comment by Immortalise** [comment]
1. Using PDR is also beneficial, I think it has a similar impact as the score differences.
2. In the adversarial prompts goal function, the `maximizable` argument is redundant.
