### ISSUE TITLE
DyVal can't be used via pypi install

### ISSUE THREAD

**Issue by GhostXu11** [microsoft/promptbench#77]
After i installed via pypi and execute examples, i found that
`
No module named 'promptbench.dyval.DAG'
`
I checked pkgs in my environment and I confirmed that this folder is missing in this path. can you solve it?

**Comment by Immortalise** [comment]
Hi, thanks for bringing this bug to us! This will be fixed in a few days. Currently you could try directly git clone this repo to use dyval instead.
