### ISSUE TITLE
About Semantic Attacks Against Vicuna

### ISSUE THREAD

**Issue by tianshuocong** [microsoft/promptbench#8]
Hi!

Thanks for your nice work!

One small question is that when I visited your [demo site](https://huggingface.co/spaces/March07/PromptBench), and I choose "Vicuna" + "MNLI" + “Semantic” + “zero-shot task”, the site return nothing. Therefore, I am confused and  could you please replenish these adversarial prompts? Many thanks!

Best wishes

<img width="813" alt="pb-issue" src="https://github.com/microsoft/promptbench/assets/90805377/0342a4f0-a67b-4bb2-8fb9-fc80d4db4a80">

**Comment by Immortalise** [comment]
Hi,

Thank you for bringing this error to our attention! We will update the attack results shortly.

**Comment by tianshuocong** [comment]
Hi!

Thank you very much!

I also noticed that when I selected model as Vicuna, and selected dataset squad_v2，UN Multi, and math, there are also not adversarial prompts.

**Comment by Immortalise** [comment]
Yes, Vicuna performs much worse on these datasets, we choose not to evaluate Vicuna on these datasets.
