### ISSUE TITLE
Want to know what code is used to implement the attention visualization in the figure below?

### ISSUE THREAD

**Issue by zl-comment** [microsoft/promptbench#83]
![微信图片_20240913235257](https://github.com/user-attachments/assets/0e2aff1c-ea7b-49aa-91b7-b7ab4ce516c4)

**Comment by kaijiezhu11** [comment]
Hi, you could refer to #78, the code is in [this file](https://github.com/microsoft/promptbench/blob/main/promptbench/utils/visualize.py).

**Comment by zl-comment** [comment]
Thanks, I already know how to run it, thank you very much

**Comment by ZJunBo** [comment]
When I run the code.  It meets a problem. ValueError: Expected input batch_size (22) to match target batch_size (1).
