### ISSUE TITLE
best 3 prompts for each categories

### ISSUE THREAD

**Issue by zhixiongzh** [microsoft/promptbench#86]
Hi,

Thanks for this great work! Could I ask where I can find the best 3 clean prompts mentioned in the paper for each categories and dataset? I can only find all prompts, but I wish to reproduce the results with only 3 (or just 1 that performs best)..

**Comment by kaijiezhu11** [comment]
Hi, it may be a little bit complicate, we have posted the results [here](https://huggingface.co/spaces/March07/PromptBench), you may retrieve the relevant results to reproduce them.

**Comment by zhixiongzh** [comment]
Hi, thanks!
